'use client';
import Badge1 from '@/assets/images/badge1.png';
import Badge2 from '@/assets/images/badge2.png';
import Badge3 from '@/assets/images/badge3.png';
import Badge4 from '@/assets/images/badge4.png';
import Badge5 from '@/assets/images/badge5.png';
import Badge6 from '@/assets/images/badge6.png';
import Badge7 from '@/assets/images/badge7.png';
import Badge8 from '@/assets/images/badge8.png';
import Badge9 from '@/assets/images/badge9.png';
import BannerImage from '@/assets/images/banner1.png';
import Bear1 from '@/assets/images/bear1.png';
import Bear2 from '@/assets/images/bear2.png';
import Bear3 from '@/assets/images/bear3.png';
import Bear4 from '@/assets/images/bear4.png';
import Bearload from '@/assets/images/bearroad.png';
import Image1 from '@/assets/images/image1.png';
import HowItWorksImage from '@/assets/images/how_it_works.png';
import { faCheckCircle } from '@fortawesome/free-regular-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Image from 'next/image';
import { useTheme } from 'next-themes';
import CircleAnimation from '../rotate';

export const Mainpage = () => {
    const { theme, setTheme } = useTheme();

    return (
        <div className={theme === 'dark' ? 'text-white' : ''}>
            <div className="container m-auto flex flex-col items-center px-5 text-center md:px-0">
                <div className="mt-12 md:mt-28">
                    <p className="text-[13px] font-medium md:text-lg">WELCOME TO MONISWAP</p>
                    <p className="max-w-[572px] text-[30px] font-medium leading-[40px] md:text-[50px] md:leading-[60px] min-w-[323px] mt-14 md:mt-16">
                        The central trading & liquidity marketplace on <br />🐻⛓️ Berachain
                    </p>
                </div>
                <Image src={BannerImage} alt="banner" className="" />
                <p className="max-w-[620px] text-sm md:text-base">
                    Moniswap is a next-generation AMM designed to serve as
                    Berachain&apos;s central liquidity hub, combining a powerful liquidity
                    incentive engine, vote-lock governance model, and friendly user
                    experience. Moniswap inherits the latest features from Velodrome V2.
                    Moniswap NFTs vote to distribute token emissions and receive
                    incentives and fees generated by the protocol.
                </p>
            </div>

            <div className="container mx-auto grid grid-cols-1 gap-5 px-5 md:grid-cols-2 md:px-10 lg:grid-cols-3 mt-14 md:mt-28">
                <div className="relative rounded-lg border border-content1 p-6 shadow-shadow1">
                    <p className="max-w-[240px] text-[13px] md:text-lg">
                        Stable & Volatile <br /> Trading for Low Fees
                    </p>
                    <FontAwesomeIcon
                        icon={faCheckCircle}
                        className="absolute right-4 top-3 text-content1 dark:text-white text-[26px] md:text-[32px]"
                    />
                </div>

                <div className="relative rounded-lg border border-content1 p-6 shadow-shadow1">
                    <p className="max-w-[240px] text-[13px] md:text-lg">
                        100% of Protocol Incentives <br /> and Fees Go to Voters
                    </p>
                    <FontAwesomeIcon
                        icon={faCheckCircle}
                        className="absolute right-4 top-3 text-content1 dark:text-white text-[26px] md:text-[32px]"
                    />
                </div>

                <div className="relative rounded-lg border border-content1 p-6 shadow-shadow1">
                    <p className="max-w-[240px] text-[13px] md:text-lg">
                        Liquid Locked Positions <br /> in the Form of NFTs
                    </p>
                    <FontAwesomeIcon
                        icon={faCheckCircle}
                        className="absolute right-4 top-3 text-content1 dark:text-white text-[26px] md:text-[32px]"
                    />
                </div>

                <div className="relative rounded-lg border border-content1 p-6 shadow-shadow1">
                    <p className="max-w-[240px] text-[13px] md:text-lg">
                        Permissionless Pools, <br /> Gauges, and Incentives
                    </p>
                    <FontAwesomeIcon
                        icon={faCheckCircle}
                        className="absolute right-4 top-3 text-content1 dark:text-white text-[26px] md:text-[32px]"
                    />
                </div>

                <div className="relative rounded-lg border border-content1 p-6 shadow-shadow1">
                    <p className="max-w-[240px] text-[13px] md:text-lg">Self-Optimizing <br /> Liquidity Flywheel</p>
                    <FontAwesomeIcon
                        icon={faCheckCircle}
                        className="absolute right-4 top-3 text-content1 dark:text-white text-[26px] md:text-[32px]"
                    />
                </div>

                <div className="relative rounded-lg border border-content1 p-6 shadow-shadow1">
                    <p className="max-w-[240px] text-[13px] md:text-lg">Anti-dilution <br /> rebases for voters</p>
                    <FontAwesomeIcon
                        icon={faCheckCircle}
                        className="absolute right-4 top-3 text-content1 dark:text-white text-[26px] md:text-[32px]"
                    />
                </div>
            </div>

            <div className="container m-auto px-5 py-16 md:flex md:px-10 md:py-28">
                <div className="space-y-3">
                    <p className="md:text-lg">How it works</p>
                    <p className="max-w-[400px] text-xl md:text-3xl">
                        Designed to reward participants that enable the sustainable growth
                        of the protocol.
                    </p>
                </div>

                <div className="md:px-24 md:pt-24">
                    {/* {theme === 'light' ? <Image src={Image1} alt="image" /> :
                        <Image src={HowItWorksImage} alt="image" />} */}
                    <CircleAnimation/>
                </div>
            </div>

            <div className="container m-auto grid grid-cols-1 gap-7 max-md:px-7 md:grid-cols-2 lg:grid-cols-4">
                <div className="rounded-lg bg-white dark:bg-dark-card shadow-shadow1 min-h-[461px] flex flex-col justify-between">
                    <div className="h-[160px] space-y-4 px-4 pt-5">
                        <p className="text-lg font-medium text-black dark:text-white">Traders</p>
                        <p className="text-[13px] tracking-wide leading-4 text-card-content-text dark:text-white">
                            Swap tokens with minimal slippage and pay some of the lowest fees
                            to MONI lockers.
                        </p>
                    </div>
                    <div className="flex items-end justify-center rounded-b-lg bg-content1 pt-10 h-[301px]">
                        <Image src={Bear1} alt="bear image" />
                    </div>
                </div>

                <div className="rounded-lg bg-white dark:bg-dark-card shadow-shadow1 min-h-[461px] flex flex-col justify-between">
                    <div className="h-[160px] space-y-4 px-4 pt-5">
                        <p className="text-lg font-medium text-black dark:text-white">Liquidity Providers</p>
                        <p className="text-[13px] tracking-wide leading-4 text-card-content-text dark:text-white">
                            Deposit the tokens used for trading on Moniswap and receive MONI
                            emissions as rewards.
                        </p>
                    </div>
                    <div className="flex items-end justify-center rounded-b-lg bg-content1 pt-10 h-[301px]">
                        <Image src={Bear2} alt="bear image" />
                    </div>
                </div>

                <div className="rounded-lg bg-white dark:bg-dark-card shadow-shadow1 min-h-[461px] flex flex-col justify-between">
                    <div className="h-[160px] space-y-4 px-4 pt-5">
                        <p className="text-lg font-medium text-black dark:text-white">Protocols</p>
                        <p className="text-[13px] tracking-wide leading-4 text-card-content-text dark:text-white">
                            Offer incentives to veMONI voters to attract votes / MONI
                            emissions to their pools, allowing them to build liquidity at a
                            low cost.
                        </p>
                    </div>
                    <div className="flex items-end justify-center rounded-b-lg bg-content1 pt-10 h-[301px]">
                        <Image src={Bear3} alt="bear image" />
                    </div>
                </div>

                <div className="rounded-lg bg-white dark:bg-dark-card shadow-shadow1 min-h-[461px] flex flex-col justify-between">
                    <div className="h-[160px] space-y-4 px-4 pt-5">
                        <p className="text-lg font-medium text-black dark:text-white">veMONI Voters</p>
                        <p className="text-[13px] tracking-wide leading-4 text-card-content-text dark:text-white">
                            Vote on which pools will earn MONI emissions and receive 100% of
                            incentives and fees for the pools they vote for. Any MONI holder
                            can lock their tokens to convert to veMONI.
                        </p>
                    </div>
                    <div className="flex items-end justify-center rounded-b-lg bg-content1 pt-10 h-[301px]">
                        <Image src={Bear4} alt="bear image" />
                    </div>
                </div>
            </div>

            <div className="my-20 shadow-shadow1 md:container max-md:mx-5 md:m-auto md:my-20">
                <div className="rounded-lg bg-white dark:bg-dark-card p-3">
                    <div className="container m-auto grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4">
                        <div className="flex flex-col items-center justify-center gap-5 rounded-lg bg-base dark:bg-dark-card py-6">
                            <p className="text-xl font-medium">$134.78M</p>
                            <p className="text-sm">TOTAL VALUE LOCKED</p>
                        </div>

                        <div className="flex flex-col items-center justify-center gap-5 rounded-lg bg-base dark:bg-dark-card py-6">
                            <p className="text-xl font-medium">$1.78B</p>
                            <p className="text-sm">TOTAL TRADING VOLUME</p>
                        </div>

                        <div className="flex flex-col items-center justify-center gap-5 rounded-lg bg-base dark:bg-dark-card py-6">
                            <p className="text-xl font-medium">$3.24M</p>
                            <p className="text-sm">TOTAL FEES GENERATED</p>
                        </div>

                        <div className="flex flex-col items-center justify-center gap-5 rounded-lg bg-base dark:bg-dark-card py-6">
                            <p className="text-xl font-medium">54.68K</p>
                            <p className="text-sm">MONTHLY USERS</p>
                        </div>
                    </div>
                </div>
            </div>

            <div className='py-20 bg-white dark:bg-darkFooter'>
                <div className="flex flex-wrap items-center justify-center gap-10">
                    <Image src={Badge1} alt="badge" />
                    <Image src={Badge2} alt="badge" />
                    <Image src={Badge3} alt="badge" />
                    <Image src={Badge5} alt="badge" />
                    <Image src={Badge6} alt="badge" />
                    <Image src={Badge7} alt="badge" />
                    <Image src={Badge8} alt="badge" />
                </div>

                <Image src={Bearload} alt="image" className="m-auto mt-32 md:mt-60" />

                <div className="flex flex-col items-center justify-center gap-10 text-center">
                    <p className="max-w-[324px] text-3xl font-bold">
                        Looking to get started with Moniswap?
                    </p>
                    <p className="border border-content2 px-10 py-4">Onboarding Guide</p>
                </div>
            </div>
        </div>
    );
}
